# Generated by Django 6.0.2 on 2026-02-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_name_student_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='classname',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('On Leave', 'On Leave')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='activity_type',
            field=models.CharField(choices=[('Attendance', 'Attendance'), ('Teacher Assignment', 'Teacher Assignment'), ('Class Activity', 'Class Activity'), ('Meeting', 'Meeting'), ('Event', 'Event'), ('Other', 'Other')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Reportcard',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
