# Generated by Django 6.0.2 on 2026-02-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_exam_subject_remove_reportcard_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.CharField(blank=True, choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('Computer Science', 'Computer Science'), ('Physical Education', 'Physical Education'), ('Art', 'Art'), ('Music', 'Music'), ('Economics', 'Economics'), ('Business Studies', 'Business Studies'), ('Literature', 'Literature'), ('Religious Education', 'Religious Education'), ('Foreign Language', 'Foreign Language')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Email',
            field=models.EmailField(default=0, max_length=225),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('Computer Science', 'Computer Science'), ('Physical Education', 'Physical Education'), ('Art', 'Art'), ('Music', 'Music'), ('Economics', 'Economics'), ('Business Studies', 'Business Studies'), ('Literature', 'Literature'), ('Religious Education', 'Religious Education'), ('Foreign Language', 'Foreign Language')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='number',
            field=models.IntegerField(max_length=13),
        ),
    ]
