# Generated by Django 6.0.2 on 2026-02-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_student_subjects_alter_teacher_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='number',
            field=models.CharField(max_length=13),
        ),
    ]
